# You can find code and docs here: https://github.com/allthings/github-action-tools
name: node-manager
description: 'Setup node and install yarn'
inputs:
  node-version:
    description: 'Node version'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install yarn
      shell: bash
      run: npm install -g yarn
