# You can find code and docs here: https://github.com/allthings/github-action-tools
name: docker-setup
description: 'Setup up docker and login'
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: '${{ env.DOCKER_LOGIN_USER }}'
        password: '${{ env.DOCKER_LOGIN_PASSWORD }}'
