name: print-logs
description: 'Prints logs by given path'
inputs:
  path:
    description: 'Location of logs'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set PATH
      shell: bash
      run: |
        echo "/bin" >> $GITHUB_PATH
        echo "/sbin" >> $GITHUB_PATH
        echo "/usr/bin" >> $GITHUB_PATH
        echo "/usr/sbin" >> $GITHUB_PATH
        echo "/usr/local/bin" >> $GITHUB_PATH
        echo "/usr/local/sbin" >> $GITHUB_PATH

    - name: print logs
      shell: bash
      working-directory: ${{ inputs.path }}
      run: >
        for log in ./*;
        do
          if [ -d ./"$log" ]; then
            for logInDir in "$log"/*;
            do
              echo "::group::$logInDir";
              /bin/cat "$logInDir";
              echo "::endgroup::";
             done;
          else
            echo "::group::$log";
            /bin/cat "$log";
            echo "::endgroup::";
          fi;
        done
